import './utils/utils.test.ts'
import './Fibonacci/fibonacci.test.ts'
import './sorting-methods/bubble-sort/bubbleSort.test.ts'
import './sorting-methods/selection-sort/selectionSort.test.ts'
import './sorting-methods/insertion-sort/insertionSort.test.ts'
import './sorting-methods/quick-sort/quickSort.test.ts'
